/*
some test API

this is a test API ![](https://commonmark.org/help/images/favicon.png)

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V20241017SayHelloResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V20241017SayHelloResponse{}

// V20241017SayHelloResponse struct for V20241017SayHelloResponse
type V20241017SayHelloResponse struct {
	Message *string `json:"message,omitempty"`
	Owner *string `json:"owner,omitempty"`
}

// NewV20241017SayHelloResponse instantiates a new V20241017SayHelloResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV20241017SayHelloResponse() *V20241017SayHelloResponse {
	this := V20241017SayHelloResponse{}
	return &this
}

// NewV20241017SayHelloResponseWithDefaults instantiates a new V20241017SayHelloResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV20241017SayHelloResponseWithDefaults() *V20241017SayHelloResponse {
	this := V20241017SayHelloResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V20241017SayHelloResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V20241017SayHelloResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V20241017SayHelloResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V20241017SayHelloResponse) SetMessage(v string) {
	o.Message = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *V20241017SayHelloResponse) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V20241017SayHelloResponse) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *V20241017SayHelloResponse) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *V20241017SayHelloResponse) SetOwner(v string) {
	o.Owner = &v
}

func (o V20241017SayHelloResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V20241017SayHelloResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	return toSerialize, nil
}

type NullableV20241017SayHelloResponse struct {
	value *V20241017SayHelloResponse
	isSet bool
}

func (v NullableV20241017SayHelloResponse) Get() *V20241017SayHelloResponse {
	return v.value
}

func (v *NullableV20241017SayHelloResponse) Set(val *V20241017SayHelloResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV20241017SayHelloResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV20241017SayHelloResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV20241017SayHelloResponse(val *V20241017SayHelloResponse) *NullableV20241017SayHelloResponse {
	return &NullableV20241017SayHelloResponse{value: val, isSet: true}
}

func (v NullableV20241017SayHelloResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV20241017SayHelloResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


